### ISSUE TITLE
Fix CAL has Segmentation Faults

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/bdd-benchmark#52] opened 2022-12-12 13:15 UTC
Since the changes in #51 that completely removed the custom code for the base cases when using Adiar, the CAL bdd package completely breaks. I cannot see anything wrong inside of the adapter, so I believe it must be an issue in the C++ interface of [CAL](https://github.com/ssoelvsten/cal).

**Comment by nhusung** [comment] 2023-08-08 18:38
Yes, I would consider it a bug in the C++ interface of CAL. The segmentation fault happens during this assignment:

https://github.com/SSoelvsten/bdd-benchmark/blob/0258a0badf347777536cc6228f3f57cf24b6d648/src/cal/adapter.h#L29

The old value of `latest_build` is the default-initialized `BDD`, which is some kind of invalid node reference:

https://github.com/SSoelvsten/cal/blob/96d5ea470f582f0b6055a201deff2959f2d1e4e9/src/calObj.hh#L124-L125

The problem is now that the implementation of the assignment operator unconditionally calls `Cal_BddFree()` on the old value:

https://github.com/SSoelvsten/cal/blob/96d5ea470f582f0b6055a201deff2959f2d1e4e9/src/calObj.hh#L154

`Cal_BddFree()` assumes that the passed node pointer is valid (it decrements reference counters), but the pointer is `NULL`. This causes the segmentation fault.

The problem should be fixed in CAL’s C++ interface, however, there is a workaround which only requires a minor change in the adapter code. Just remove the assignment and initialize `_latest_build` in the initializer list:

```c++
  cal_bdd_adapter(const uint32_t bdd_varcount)
      : __mgr(bdd_varcount), varcount(bdd_varcount), _latest_build(bot()) {
    // Disable dynamic variable reordering
    __mgr.DynamicReordering(Cal::ReorderTechnique::NONE);
  }
```

**Comment by nhusung** [comment] 2023-08-08 18:47
After fixing the above, CAL still SEGFAULTs inside the destructor of `Cal`, or more precisely `CalPageManagerQuit()`:

https://github.com/SSoelvsten/cal/blob/96d5ea470f582f0b6055a201deff2959f2d1e4e9/src/calMemoryManagement.c#L157-L158

I haven’t investigated that problem further. There is also a quick & dirty fix: Just wrap the [`Cal __mgr` field](https://github.com/SSoelvsten/bdd-benchmark/blob/0258a0badf347777536cc6228f3f57cf24b6d648/src/cal/adapter.h#L17) in a union (i.e. `union { Cal __mgr; };`). This will cause a memory leak, but in case of the benchmarks here, the destructor is only run right before the program exits. Hence, we can also let the system clean up :man_shrugging:

**Comment by SSoelvsten** [comment] 2023-08-10 09:44
Thank you so much for investigating where CAL is breaking!

Since CAL's C++ interface is one that I am trying to make (due to my research I have to try and bring it back from the grave), I am definitely thinking to fix it on CAL's end with a conditional.

**Comment by SSoelvsten** [comment] 2023-08-10 10:03
I wonder why I just made [this issue](https://github.com/SSoelvsten/cal/issues/10) rather than fixing it.

**Closed** 2023-08-10 11:11 UTC
Labels: 🔥 bug, help wanted, 🔌 adapter
